// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7rNEoa3R-TtRn4vLacp8u0mbfsbcNCM',
    appId: '1:192922301468:web:025764e9a78568cff49bd9',
    messagingSenderId: '192922301468',
    projectId: 'project-masjid-sabilillah',
    authDomain: 'project-masjid-sabilillah.firebaseapp.com',
    storageBucket: 'project-masjid-sabilillah.firebasestorage.app',
    measurementId: 'G-2LHD4HYC7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARHl32zbpxOCFLQM9TDyARmLEnuKcEuBY',
    appId: '1:192922301468:android:9036181196e26b8cf49bd9',
    messagingSenderId: '192922301468',
    projectId: 'project-masjid-sabilillah',
    storageBucket: 'project-masjid-sabilillah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2wo0yJuPaU8Nd2pd7p4Lh9OpcttusHV8',
    appId: '1:192922301468:ios:0dd0f1bf8a335720f49bd9',
    messagingSenderId: '192922301468',
    projectId: 'project-masjid-sabilillah',
    storageBucket: 'project-masjid-sabilillah.firebasestorage.app',
    iosBundleId: 'com.example.masjidSabilillah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2wo0yJuPaU8Nd2pd7p4Lh9OpcttusHV8',
    appId: '1:192922301468:ios:0dd0f1bf8a335720f49bd9',
    messagingSenderId: '192922301468',
    projectId: 'project-masjid-sabilillah',
    storageBucket: 'project-masjid-sabilillah.firebasestorage.app',
    iosBundleId: 'com.example.masjidSabilillah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7rNEoa3R-TtRn4vLacp8u0mbfsbcNCM',
    appId: '1:192922301468:web:c045c1b8cc906570f49bd9',
    messagingSenderId: '192922301468',
    projectId: 'project-masjid-sabilillah',
    authDomain: 'project-masjid-sabilillah.firebaseapp.com',
    storageBucket: 'project-masjid-sabilillah.firebasestorage.app',
    measurementId: 'G-W4G0PV5LMD',
  );
}
